### PR TITLE
Reusable methods

### PR DESCRIPTION
**Pull request by SimonCropp**
Disclaimer: i know nothing about javascript

changes usages to this

```
<script src="../src/ga-lite.js"></script>
<script>
var galite = new GaLite('UA-XXXXXX');
galite.addToPageLoad();
</script>
```

but also exposes this

```
galite.fireEvent(
    'event',
    {
        'ec': 'My Event Category',
        'ea': 'My Event Action'
    }
);
```

### CODE REVIEW

**Comment by SimonCropp** [comment]
@jehna given my lack of experience with JS, i dont necessarily expect this to be merged as-is. feel free to cherry pick any changes u find useful and discard the PR :)

**Comment by SimonCropp** [comment]
Any thoughts?

**Comment by jehna** [comment]
Thank you for the pull request.

This pull request introduces non-backwards compatible changes, so I moved the bug fix to its own pull request to fix the `1.x` version for now.

I think I'll refactor this approach a bit to support the current official `analytics.js` format, as specified in the issue #14 and open up a `2.0` branch to do this.

**Comment by SimonCropp** [comment]
@jehna happy for u to take any of this to form a new PR. as i said i am a JS noob and prob made some mistakes

**Comment by jehna** [comment]
Alright, spent last night working on the version 2's public API #7 

You can see the current progress in the `public-api` branch. It still needs some additional methods to be checked in order to be merged in `version-2.0` branch, but the basic public API looks quite good for now.

Closing this pull request in favour of the version 2.

**Pull request closed without merging**
